services:
  app:
    container_name: backend
    image: lypandrew87/spanish-amigo:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
  mongodb:
    restart: always
    container_name: database
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
    external: true
